print("Divadlo Pěst na oko")
print("Vítejte v online rezervaci vstupenek")
print("Pro vstup do systému je potřeba registrace")
uzivatelskeJmeno = input("Zadej uživatelské jméno: ")
vek = input("Zadej věk: ")